monitoring:
    user: ENC[AES256_GCM,data:6cR4Sipo,iv:dIALW5AFbDe3vk1WRt8/H1EPrLMi4qfO0UShASjzSFs=,tag:3MfFRbGgekbVPSd41WjGFg==,type:str]
    password: ENC[AES256_GCM,data:2zkEFedW,iv:IYNdBZXERwknmwiKzvsYetN5FlL+Xp1Ugs8Lbak6tgE=,tag:iXU1q1eo5q5/PGEr4+60Lw==,type:str]
sops:
    lastmodified: "2026-03-29T23:57:32Z"
    mac: ENC[AES256_GCM,data:OgLIMQKMGs9KvpDojD9qgMXqW9MXH722vZtZ3dLpHJZCYnG2bYGsGzjGfW+vt4/GvNkVBEZ91WoqML8oAF+hPHKSVv2wDHmiSXRTV6eIBvfgrDCc+EQ5OEJkOww6k7yXFK3MfwQ4zx+T9Ax55dHiGrITC0rWY31FAyyuT848Ba0=,iv:B4iFZeFYmuRv8/FG3ZN/B8CYE6omOobUqUNyg1nCOHU=,tag:tLo9Mb2Vz7xfArEynVj6gw==,type:str]
    pgp:
        - created_at: "2026-03-29T23:57:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA2R7qhaxv62MAQv/RwhT3+Fas//kdOjdot+R9I9v2wfJV/XAJ4bQJNoQTN4+
            EM+ulE4IDlTf7D96qORXt6FRQ1H9opAfqW9pbRi5EhOjSwczBUhgTLcanuSs+iAM
            ZdexkZJscRilyxhCpuevMtPU4Bx+oau0YLgpSI8hI3w0VznKskbyADjRI02rlyW/
            xb5Y4lGsjP5/qsFMbVzbi5IiMPPWcqq4c2/7Dv67OtPTJrnshkuNFlu75UzIklrf
            qqPT1sn82bNwgg6VnivuryMbRlmFHpZCPrr7jCtPir8Z3cwc4w3uNZ6tFGXormgv
            uC3+GJ0cGNjdrtpZzvAPRQCEvtdTop2psa551v25rbCHE/FmwGuuTzU+NLS1TwAm
            oCbiivQKNBpM3Yp8IdWnKTsTcrRJBTfqOPWE2eY5h8ZD3qE/zJloOFD5DJ/dGUu0
            hhWUUB334COlzp6EdwODhkAwnFCwvBwfagJCT1jaI/rmR2eXac2G4lbPA9yT4sJl
            BI+4aUmRVG9boj7Fy8b61GgBCQIQc/LNFNukv07RT+WLN01C1XGyE1HIlQQJG/VV
            7Ii7TITvlzZilYLibKq6FWEwBaDwaDXIw8qcUPHBeBqCy0P2X9JJMddrN+qpFMpA
            Ux78s+/Z76almcJxi+tMwSMhkjcDlZ3ujA==
            =MWlu
            -----END PGP MESSAGE-----
          fp: EDB084ED8DD155B595A672C8E411EE12A8F5C363
    unencrypted_suffix: _unencrypted
    version: 3.12.2
