keys:
  - &paul 456ED7C90F5F332CAE5D0B9C6A92EA2CBF14A770

creation_rules:
  - path_regex: infra/secrets.yaml
    key_groups:
      - pgp: [ *paul ]

  - path_regex: hosts/nextcloud/secrets.yaml
    key_groups:
      - pgp: [ *paul ]
