proxmox:
    endpoint: ENC[AES256_GCM,data:PRBATzyLREutEVVqmmDs5cbqppZiXhPtAzqms358ZspdFMAG,iv:eiOdjiaT0udMdqGhDst5nmKWIzshFeywx/+Qe56L+EY=,tag:SUuoGji9ChMO5vJx/zHBOA==,type:str]
    api_token_id: ENC[AES256_GCM,data:0XcrfJW9HAtA/qoXXSCLDVRKREDGZKI=,iv:n/KhsXAVKstBN3ncuGVll4RHQBO3y1F/B0jfmVULWdI=,tag:ND61msFopMFs2UsmxItV0g==,type:str]
    api_token_secret: ENC[AES256_GCM,data:qc30RSWtbHQ6mOlUi8UGQ0Y21/Kbmmh8qn8VTli7KhELLF5P,iv:OOMscTdJA4lLJ6rX8wMvtqKhDSKMWz74bCgjL9Tux2I=,tag:4r+ONK98ZRhQ65SYv7PY+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-28T03:04:08Z"
    mac: ENC[AES256_GCM,data:LqTFS2djhAvW85Mj2wTR6M3RVGn+YgHuJYOLAeJAQU6IN/8ZO55aXiyLLiBlJsQluxwHHdbI86t+BYlu0Bda7ceABtbB4CC30MrqhuL9987SOJQDyzVOZGwQehth35T5p2+IAHdnZ6FtogUsbGjjmdGWjCViiBy5v1kjdqSHCDQ=,iv:8gjpjgMy4heco7TEsNZXcmjcLXBbHdlJnmiAf7Fjbas=,tag:UellUKUVDD0TeYEXU3kpPg==,type:str]
    pgp:
        - created_at: "2025-11-28T03:04:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA2R7qhaxv62MAQwAlZt3b4r3qG9DJh6xFN/ZdYPyUPzoFlDXI8PK1K9nKkmU
            wkMUZgz8EPF9A1nJUPCZZq9g0tvVX7K7XxDROL3fhINncASSIB36K0Hgyve0F6zO
            X8yQhpGY4Q9VFINevrjX/rRGMFfDX16zlREq17K5NQdQzlqclYHn24vmPc3YQY2g
            /LHttEoRftuhoWDRCjD7IaqJ3uKhUrTKdBo3jfq6zPsTtwBKUCkjstqEb5kc/ihp
            VBuu2L/b3NchxPrPfrvqmIg15qQoJtucZ3UvyWHUTvMrcA0mrJ+u/NqHmuOAfg8u
            5gozI7z++JehSRfYhjmEEtVn7uXBq8yJwhCws17WSWXMB+b81COcx+c2qE/dea1/
            FAkwoUpDG7i7g4JltHToZUG4I6VyH65Y6Xqg5DliosSJmd214Jd/UmSpeLoi+DkQ
            yjfYEXHVu+IM0nxT0WkZAVQHeCAeUGesU0WyT6O3z6r5heM4mdTnlNLxNSwXhOHw
            5ebZd+q+ouwk+k52o1e50l4BhlSBneTRHXKrgcLqkN2x0J3Hv6HQyM1nwy5rX2JE
            wEZbDPD+I2qoKJwA18EX0LjPSkcTw4plRWB+b/qIviEyJyxp0tTqozFt6fmS4Ghn
            WzQEpYo+x2SW6d4d/XJ3
            =Hvi1
            -----END PGP MESSAGE-----
          fp: EDB084ED8DD155B595A672C8E411EE12A8F5C363
    unencrypted_suffix: _unencrypted
    version: 3.9.4
