minecraft:
    user: ENC[AES256_GCM,data:GArcBLKS,iv:xfiu+Aeu3sG2+RvWu8cxN5JGIQWgiSgczuIVllouZRI=,tag:mdkHAhLAd5TbAj3me/umVw==,type:str]
    password: ENC[AES256_GCM,data:kTpwMkRe,iv:2A9/LS5vfj9rqjBlNZyirpG+BxihkNu7gcV1twYNhXs=,tag:XCvCCDCEZLDlJzJkJr7Fhg==,type:str]
sops:
    lastmodified: "2026-04-18T20:23:09Z"
    mac: ENC[AES256_GCM,data:hoGrt/KcjqLPLMqo/5yEj4EiQY/aMKjuWoZFdSjRPor3hVkUgupfXtw6QF27Co4nYhNc5ge8DVAnSGH/LC/IkUiIYscRMHZHUWfv/qagixMriBL0pDHGZ90Q1P6lylqM9QP8I8jS+4zvrOJ84uSDP6lK/oqXxD6JN/mYd5qHxaY=,iv:c7epneN11GHEBMwryH4kQRo54suDsOtyhRGh4MK2KFo=,tag:+GSvHpWzUePsmMTuMF/T2w==,type:str]
    pgp:
        - created_at: "2026-04-18T20:23:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA2R7qhaxv62MAQv+LMCdEM/Ku8XgsJ7yLEQUqmMZaVs8XJXBX0jRv2NI0cZQ
            RIR7+lnfjUm6kzC/SuCCH5yW6+bhclGsofVcADTcTo9KxQRqu6oR2wiMa7yVqaLN
            vXSam554cSOqvxf75dpLIOvL50sKpb1wFdHjQt7wedmEcXNtenZwvU5jUTL/MfWK
            s1i/LRQ+36BH3eyM0m2i1gOVpFv/L7rSZ0qJDA2k6RmcbKelW6l1b8CHLTFG2WdQ
            Icvg7F9Th3Z8mUD7amoA0vbyROGOHYU+zPb1YpyXyhDXPQK45JPp6rooRNliWbYC
            rFHkCbCY1mTKbj95Mmg4Vzpe4SoJf04mQJHo+zViquOWnuR95jIWjUvGs4FFsD+/
            7D6+KgLy6uyiuGS6C+Thlp9K1zVbOqFYFUaM1d9u5f3dr7gaEapemMgVyJ6nlfXO
            zeh7gRt6mQj/nEBz+g0xE0EzJjGrsLy72s5e7D1v2xGKt5+IqWHRpyQBhwof7vu3
            RvY5F1Oaz2wwdoCa+dv11FsBCQIQmnjE83o5oze+apbcW+IjYXSyPvif9shILAX2
            3XsVl1usKJj0vS0ZcvtjjuNNYJDfqft53ArtRPe9eB8FURjSXDtquyFwaQvLgHZo
            q1EcwPa8Zlb7dZ9n
            =WzQF
            -----END PGP MESSAGE-----
          fp: EDB084ED8DD155B595A672C8E411EE12A8F5C363
    unencrypted_suffix: _unencrypted
    version: 3.12.2
