stirlingpdf:
    user: ENC[AES256_GCM,data:wtzfoU6j,iv:T/FOLM6Hrtb1K3z9/mb29VXv7pSvj8zFJ3hZAUyb4SU=,tag:ZFbJLftfGkvL7blnenA6BA==,type:str]
    password: ENC[AES256_GCM,data:hmrfmc7N,iv:48KYopCCvTZS0A9EIfZ5YsCtdZPkEnor+lvC/GqxzC0=,tag:GW/a7yWkz7TuIbyqUiqgKQ==,type:str]
sops:
    lastmodified: "2026-03-29T19:37:26Z"
    mac: ENC[AES256_GCM,data:64fJ+CL7AfH2hdcR0y3dtCBVYYhwPgQVdp0q+t+5Sve79FlZ+IUgvHdOC0sGpJN0k2C4cU5y84f97FNyrfdmh+z0mNlUddNKaOy/YzJKBNxkFCj3QZlpOYeCZqFR6cnA0nifiy8Ps4POtANFT6CNBBZII4SJ78p+pF7TJ4WE4So=,iv:Lww2tEXrWm0Rxal9KkYCSivgWqcmKLWox7pk2c+MuwE=,tag:50elpHAmfUrS/sm9fE76wA==,type:str]
    pgp:
        - created_at: "2026-03-29T19:37:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA2R7qhaxv62MAQwAvoAbvHIZwumnrbb0F8x4AdhkKBtFDTclTtuYhC600as9
            91P1kByI+VI2HCAleQ4oD+TbOmljDNNEyXYwRffguuqriGoh7YC3+NGctJMLI5aH
            GD0c2udFeUyIiYFIFFMgr+jjw3ww50sh0nCDm6gmbVwMVetrCcDm5GWcZpSc8O98
            DS9hFAb7npkftk5rlXK56lgD4FuFsMm7WSFqxI3bASC3RGxvU55HCQXnhVSzBhJP
            mlk+c/fTfWmCP8WKjnvM3doIIB2HZSN4GJX14VBJ0HVzVcfJdcfkrIiGephY4iBg
            +tODd0mUvV9BWZ0M1Narn2LyloETq6FtUpOlRix7Xy+IHHAXPO+nCIp8PfypwnDE
            +hlCAeZOzWPrdqKfComgwBxAP0tJBWsRLalXLjNrSx3jfHCrt+xSP+Kqh+mawHJe
            KoLlPMoRYqJJa6464LNkqOGhlrcKOvrYahe0X+uBTBQ1dIzlK6afQTASRYBgZEhQ
            cnc7U+f5qJQgVFcShjjR1GYBCQIQcQJyRsbRYWfo216v6h8/6/aHPyqaIABmNFnu
            VOqvSWxvtG0D6y6h41p+/xzK8Z++CdK3V5qDBGAOYcxKPtMlK3SbyVX1arr8f+BP
            Z5/9ZHKwhnI+vvoEa7yztRUaagwavkQ=
            =WFJ3
            -----END PGP MESSAGE-----
          fp: EDB084ED8DD155B595A672C8E411EE12A8F5C363
    unencrypted_suffix: _unencrypted
    version: 3.12.2
